# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-02 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz_content', '0029_remove_checklist_category'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='checked_items',
            field=models.ManyToManyField(to='biz_content.ChecklistItem'),
        ),
    ]
