# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_project_checked_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='checked_items',
        ),
        migrations.RemoveField(
            model_name='project',
            name='checklists',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
