# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-21 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('biz_content', '0002_auto_20161121_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='biz_content.Category'),
        ),
    ]
