# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-21 17:04
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('biz_content', '0004_auto_20161121_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='checklist',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='biz_content.Checklist'),
        ),
    ]
