# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-21 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('biz_content', '0005_auto_20161121_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='item',
            field=wagtail.wagtailcore.fields.StreamField([('text', wagtail.wagtailcore.blocks.CharBlock(classname='text', max_length=255, null=True)), ('completed', wagtail.wagtailcore.blocks.BooleanBlock(default=False, null=True)), ('order_num', wagtail.wagtailcore.blocks.IntegerBlock(default=0, null=True))], null=True),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='checklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='biz_content.Checklist'),
        ),
    ]
