# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-21 17:40
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('biz_content', '0006_auto_20161121_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='item',
        ),
        migrations.AddField(
            model_name='checklist',
            name='items',
            field=wagtail.wagtailcore.fields.StreamField([('text', wagtail.wagtailcore.blocks.CharBlock(classname='text', label='Checklist Text', max_length=255, null=True))], null=True),
        ),
    ]
