# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-21 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('biz_content', '0007_auto_20161121_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('resources', wagtail.wagtailcore.fields.StreamField([('phone_number', wagtail.wagtailcore.blocks.IntegerBlock(classname='phone_number', help_text='Add a Phone Number', label='Phone Number', max_length=255, null=True)), ('email', wagtail.wagtailcore.blocks.CharBlock(classname='email', help_text='Add an email', label='Email', max_length=255, null=True)), ('link', wagtail.wagtailcore.blocks.IntegerBlock(classname='text', help_text='Add resource link', label='Resource Link', max_length=1000, null=True))], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StepPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('date', models.DateField(verbose_name='Post date')),
                ('intro', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='items',
            field=wagtail.wagtailcore.fields.StreamField([('text', wagtail.wagtailcore.blocks.CharBlock(classname='text', help_text='Add a Checklist Item', label='Checklist Text', max_length=255, null=True))], null=True),
        ),
        migrations.AddField(
            model_name='contentparagraph',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_paragraph', to='biz_content.StepPage'),
        ),
    ]
