# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-21 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('biz_content', '0008_auto_20161121_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentparagraph',
            name='header',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contentparagraph',
            name='resources',
            field=wagtail.wagtailcore.fields.StreamField([('phone_number', wagtail.wagtailcore.blocks.IntegerBlock(classname='phone_number', help_text='Add a Phone Number', label='Phone Number', max_length=255, null=True)), ('email', wagtail.wagtailcore.blocks.EmailBlock(classname='email', help_text='Add an email', label='Email', null=True)), ('link', wagtail.wagtailcore.blocks.IntegerBlock(classname='text', help_text='Add resource link', label='Resource Link', max_length=1000, null=True))], null=True),
        ),
        migrations.AlterField(
            model_name='steppage',
            name='date',
            field=models.DateTimeField(verbose_name='Post date'),
        ),
    ]
