# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-21 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz_content', '0010_auto_20161121_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentparagraph',
            name='subheader',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
