# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-22 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biz_content', '0012_auto_20161122_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='steppage',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='biz_content.Checklist'),
        ),
    ]
