# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-22 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('biz_content', '0013_steppage_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='steppage',
            name='header_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
