# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-22 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz_content', '0014_steppage_header_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='steppage',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
