# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-22 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz_content', '0015_steppage_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steppage',
            name='intro',
        ),
    ]
