# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-25 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('biz_content', '0016_remove_steppage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='steppage',
            name='link_page',
            field=models.ForeignKey(blank=True, help_text='Choose an existing page if you want the link to point somewhere inside the CMS.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
