# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-28 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz_content', '0018_steppage_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='page',
        ),
    ]
