# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-28 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biz_content', '0019_remove_checklist_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steppage',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='biz_content.Checklist'),
        ),
    ]
