# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-28 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz_content', '0022_auto_20161128_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentparagraph',
            name='header',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
