# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-29 16:12
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('biz_content', '0023_auto_20161128_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentparagraph',
            name='resources',
            field=wagtail.wagtailcore.fields.StreamField([('phone_number', wagtail.wagtailcore.blocks.IntegerBlock(classname='phone_number', help_text='Add a Phone Number', label='Phone Number', max_length=255, null=True)), ('email', wagtail.wagtailcore.blocks.EmailBlock(classname='email', help_text='Add an email', label='Email', null=True)), ('link', wagtail.wagtailcore.blocks.URLBlock(classname='text', help_text='Add resource link', label='Resource Link', max_length=1000, null=True))], blank=True, null=True),
        ),
    ]
