# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-30 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz_content', '0025_auto_20161130_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='checklist',
        ),
        migrations.DeleteModel(
            name='ChecklistItem',
        ),
    ]
