# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('biz_content', '0026_auto_20161130_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='page',
        ),
        migrations.AlterField(
            model_name='steppage',
            name='link_page',
            field=models.ForeignKey(blank=True, help_text=('Choose an existing page if you want the link ', 'to point somewhere inside the CMS.'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='steppage',
            name='page_content',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title', icon='title')), ('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('email', wagtail.wagtailcore.blocks.EmailBlock(classname='email', help_text='Add an email', label='Email', null=True, template='biz_content/content_blocks/email_block.html')), ('phone_number', wagtail.wagtailcore.blocks.IntegerBlock(classname='phone_number', help_text='Add a Phone Number', label='Phone Number', max_length=255, null=True, template='biz_content/content_blocks/phone_block.html')), ('link', wagtail.wagtailcore.blocks.StructBlock((('link_text', wagtail.wagtailcore.blocks.CharBlock()), ('link_url', wagtail.wagtailcore.blocks.URLBlock())), classname='text', help_text='Add resource link', label='Resource Link', null=True, template='biz_content/content_blocks/url_block.html'))), blank=True, null=True),
        ),
    ]
