# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-02 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz_content', '0028_auto_20161202_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='category',
        ),
    ]
