# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-06 23:00
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('biz_content', '0030_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steppage',
            name='page_content',
            field=wagtail.wagtailcore.fields.StreamField([(b'heading', wagtail.wagtailcore.blocks.CharBlock(classname=b'full title', icon=b'title')), (b'paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), (b'email', wagtail.wagtailcore.blocks.EmailBlock(classname=b'email', help_text=b'Add an email', label=b'Email', null=True, template=b'biz_content/content_blocks/email_block.html')), (b'phone_number', wagtail.wagtailcore.blocks.IntegerBlock(classname=b'phone_number', help_text=b'Add a Phone Number', label=b'Phone Number', max_length=255, null=True, template=b'biz_content/content_blocks/phone_block.html')), (b'alert_text', wagtail.wagtailcore.blocks.CharBlock(classname=b'alert_text', help_text=b'Add Alert Text', label=b'Alert Text', max_length=2000, null=True, template=b'biz_content/content_blocks/alert_text.html')), (b'link', wagtail.wagtailcore.blocks.StructBlock([(b'link_text', wagtail.wagtailcore.blocks.CharBlock()), (b'link_url', wagtail.wagtailcore.blocks.URLBlock())], classname=b'text', help_text=b'Add resource link', label=b'Resource Link', null=True, template=b'biz_content/content_blocks/url_block.html'))], blank=True, null=True),
        ),
    ]
