# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-06 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz_content', '0030_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='project',
            name='checked_items',
        ),
        migrations.RemoveField(
            model_name='project',
            name='checklists',
        ),
        migrations.RemoveField(
            model_name='steppage',
            name='checklist',
        ),
        migrations.DeleteModel(
            name='Checklist',
        ),
        migrations.DeleteModel(
            name='ChecklistItem',
        ),
    ]
