# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-06 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('biz_content', '0031_auto_20161206_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.CharField(max_length=255)),
                ('checklist', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='biz_content.StepPage')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='checklists',
            field=models.ManyToManyField(to='biz_content.StepPage'),
        ),
        migrations.AddField(
            model_name='project',
            name='checked_items',
            field=models.ManyToManyField(to='biz_content.ChecklistItem'),
        ),
    ]
