# -*- coding: utf-8 -*-

# Generated by Django 1.9.7 on 2016-12-07 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz_content', '0031_auto_20161206_2300'),
        ('biz_content', '0032_auto_20161206_2308'),
    ]

    operations = [
    ]
