# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-10 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('biz_content', '0036_collectionpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(help_text='The name of the department.', max_length=255)),
                ('phone', models.CharField(help_text="The departnment's phone number", max_length=255)),
                ('address', models.CharField(help_text='Department address.', max_length=255)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
