# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-12 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz_content', '0037_footersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersettings',
            name='address',
        ),
        migrations.AddField(
            model_name='footersettings',
            name='city_state_zip',
            field=models.CharField(help_text='E.g. Syracuse, NY 13202.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='footer_description',
            field=models.CharField(help_text='E.g. Syracuse, NY 13202.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='street_address',
            field=models.CharField(help_text="The department's street address, e.g. 1234 Main St.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='department_name',
            field=models.CharField(help_text='The name of the department.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='phone',
            field=models.CharField(help_text="The departnment's phone number", max_length=255, null=True),
        ),
    ]
