# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-19 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz_content', '0038_auto_20161212_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionpage',
            name='date',
        ),
        migrations.RemoveField(
            model_name='steppage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='steppage',
            name='date',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
