# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-20 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0015_fill_filter_spec_field'),
        ('biz_content', '0039_auto_20161219_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpage',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
