# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-04 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('biz_content', '0042_add_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersettings',
            name='footer_description',
        ),
        migrations.RemoveField(
            model_name='steppage',
            name='link_page',
        ),
        migrations.AddField(
            model_name='footersettings',
            name='first_link',
            field=models.ForeignKey(blank=True, help_text='Choose a page to display in the 1st column of the footer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='second_link',
            field=models.ForeignKey(blank=True, help_text='Choose a page to display in the 2nd column of the footer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='third_link',
            field=models.ForeignKey(blank=True, help_text='Choose a page to display in the 3rd column of the footer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='steppage',
            name='next_step',
            field=models.ForeignKey(blank=True, help_text='Choose the next step to link to at the bottom of the page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='steppage',
            name='previous_step',
            field=models.ForeignKey(blank=True, help_text=('Choose the previous step to link to ', 'at the bottom of the page.'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
