# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-05 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz_content', '0043_auto_20170104_1935'),
        ('biz_content', '0044_auto_20170105_0018'),
    ]

    operations = [
    ]
