# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-09 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz_content', '0045_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steppage',
            name='next_step',
        ),
        migrations.RemoveField(
            model_name='steppage',
            name='previous_step',
        ),
    ]
