# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-25 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz_content', '0050_auto_20170123_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='checked_items',
        ),
        migrations.RemoveField(
            model_name='project',
            name='checklists',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
