# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-07 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz_content', '0052_standalonecontentpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BizLicenseSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
