# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-21 00:19
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('biz_content', '0053_bizlicensesearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='standalonecontentpage',
            name='sidebar_images',
            field=wagtail.wagtailcore.fields.StreamField((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()),), null=True),
        ),
    ]
