# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-21 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz_content', '0054_standalonecontentpage_sidebar_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_id', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
