# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-08 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0030_index_on_pagerevision_created_at'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='selected_pages',
            field=models.ForeignKey(blank=True, help_text='Choose pages to appear in the popular pages homepage section ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
