# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-09 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('biz_content', '0036_collectionpage'),
        ('home', '0003_homepage_selected_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSelectedPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='selected_pages',
        ),
        migrations.AddField(
            model_name='homepageselectedpages',
            name='page',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_pages', to='home.HomePage'),
        ),
        migrations.AddField(
            model_name='homepageselectedpages',
            name='step_pages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='biz_content.StepPage'),
        ),
    ]
