# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-19 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20161209_0732'),
        ('home', '0003_homepage_header_img'),
    ]

    operations = [
    ]
