# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-07 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='value_prop',
            field=models.CharField(help_text='e.g. loan, 30hrs of mentoring', max_length=255, verbose_name='outcome'),
        ),
    ]
